sonar.projectKey=Thatoneuglyfool_sit223-jenkins-express-pipeline
sonar.organization=thatoneuglyfool
sonar.host.url=https://sonarcloud.io

sonar.sources=lib,index.js,app.js
sonar.tests=pipeline-tests

sonar.exclusions=node_modules/**,coverage/**,examples/**,test/**
sonar.sourceEncoding=UTF-8