sonar.projectKey=Thatoneuglyfool_sit223-jenkins-express-pipeline
sonar.organization=Thatoneuglyfool
sonar.host.url=https://sonarcloud.io

sonar.sources=lib,index.js,app.js
sonar.tests=test

sonar.exclusions=node_modules/**,coverage/**,examples/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8